[package]
name = "corrOSion"
version = "0.4.0"
authors = ["Andre Richter <andre.o.richter@gmail.com>", "Vegard Kamsvåg <vegardkamsvaag@gmail.com>"]
edition = "2021"

[profile.release]
lto = true

[features]
default = []
bsp_rpi3 = []
bsp_rpi4 = []

[[bin]]
name = "kernel"
path = "src/main.rs"

## -------------------------
## dependencies
## -------------------------
[dependencies]
# Platform specific dependencies
[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64-cpu = { version = "9.x.x" }
